# Generated by Django 4.1.4 on 2023-05-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_biographie_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='couvertureimg',
            field=models.ImageField(default='timeline-1.jpg', upload_to='profile_images'),
        ),
    ]
